# Generated by Django 2.1 on 2019-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190709_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrticlepost',
            name='total_vies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
