# Generated by Django 2.1 on 2019-07-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_atrticlepost_total_vies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atrticlepost',
            old_name='total_vies',
            new_name='total_views',
        ),
    ]
